### ISSUE TITLE
Newbie has a problem

### ISSUE THREAD

**Issue by jperson19468** [ChangemakerStudios/Papercut#88] opened 2017-11-13 16:30 UTC
Trying to send email from localhost machine using php, gmail & xampp v3.2.2 Thought papercut would be a good way to test and debug
Download Papercut.Setup.exe to  "C:\xampp\htdocs" directory
Ran Papercut.Setup.exe  said it was installation was successful
I have the open envelope in my taskbar
created program:
```php
    $to = "jperson19468@gmail.com";
    $subject = "My subject";
    $txt = "Hello world!";
    $headers = "From: webmaster@example.com" . "\r\n" . "CC: somebodyelse@example.com";
    mail($to,$subject,$txt,$headers);
```

When I run the program I get a blank screen
I am running as http:\\localhost\test_sendmail.php
I do have a send mail directory under xampp but I changed the name on it
Should I put it back?
I also do have a line in my php.ini file that reads the following:
"sendmail_path = "\"C:\xampp\sendmail\sendmail.exe\" -t"  "
Thanks

**Comment by jijiechen** [comment] 2017-11-14 11:27
Hi @jperson19468  Did you configure your SMTP server to Papercut?
Please refer to http://php.net/manual/en/mail.configuration.php

**Comment by jperson19468** [comment] 2017-11-15 02:28
OK, here is my php.ini file under the mail function:
[mail function]
; For Win32 only.
; http://php.net/smtp
;SMTP=localhost
; http://php.net/smtp-port
;smtp_port=25

SMTP=smtp.gmail.com
smtp_port=587
sendmail_from = jperson19468@gmail.com
sendmail_path = "\"C:\xampp\sendmail\sendmail.exe\" -t"      

; For Win32 only.
; http://php.net/sendmail-from
;sendmail_from = me@example.com

Change the following line:
SMTP=smtp.gmail.com to SMTP=smtp.Papercut.com ?

**Comment by jijiechen** [comment] 2017-11-15 03:27
For testing purposes, you should modify your php.ini and configure you `SMTP` to the endpoint where Papercut locates at, e.g. `localhost`, and default port is `25`.
 
Papercut is an independent mail service, instead of a mail client, it actually acts as the SMTP service itself.

**Comment by jperson19468** [comment] 2017-11-15 04:03
smtp_port=587 changed to smtp_port=25
SMTP=smtp.gmail.com changed to SMTP=localhost

**Comment by jperson19468** [comment] 2017-11-16 02:13
My php.ini file under the mail function looks likes this now:
[mail function]
; For Win32 only.
; http://php.net/smtp
;SMTP=localhost
; http://php.net/smtp-port
;smtp_port=25

**SMTP=localhost
smtp_port=25**
sendmail_from = jperson19468@gmail.com
sendmail_path = "\"C:\xampp\sendmail\sendmail.exe\" -t"      

; For Win32 only.
; http://php.net/sendmail-from
;sendmail_from = me@example.com

**Comment by jperson19468** [comment] 2017-11-16 02:38
I am getting this error now
This site can’t be reached

localhost refused to connect.
Search Google for localhost test sendmail
ERR_CONNECTION_REFUSED

**Comment by jijiechen** [comment] 2017-11-20 03:15
You can check if Papercut shows your mail message on the UI to confirm whether it receives your mail message. 
The log output about failures on starting HTTP server does not matter in your case.

Regarding the blank page output, it depends on your PHP code. You got the blank page because you didn't write any code to write something, e.g. invoke `echo` after the `mail` call.

**Comment by jperson19468** [comment] 2017-11-23 01:28
OK, here are the latest things that I have 
email script for testing
`<?php
$to = "Papercut@Papercut.com";
$subject = "My subject";
$txt = "Hello world!";
$headers = "From: webmaster@example.com" . "\r\n" .
"CC: somebodyelse@example.com";

$success = mail($to,$subject,$txt,$headers);
if (!$success) {
    $errorMessage = error_get_last()['message'];
    echo 'Error error you have a error '.$errorMessage;
}else{
 echo 'OK Done';
}

?>`
To start Papercut:
I clicked on the following file:
Papercut.exe
This file was located at:
C:\xampp\htdocs
Xampp was not runnung

The papercut gui came up with the default mail message in it that says **Welcome to Papercut!**
I now start Xampp & apache
I run the test email by typing in the following:
http:\\localhost\test_sendmail.php
I received the following message:
OK Done

Default mail message still displays in papercut gui no new email
Here is what the log reads in the papercut gui:
11/22/2017 8:10:11 PM [Information] Server Ready - Listening for New Connections "0.0.0.0":25 
11/22/2017 8:10:11 PM [Information] Starting Server Smtp 
11/22/2017 8:10:07 PM [Information] Server Ready - Listening for New Connections "127.0.0.1":37402 
11/22/2017 8:10:07 PM [Information] Starting Server Papercut 
11/22/2017 8:10:06 PM [Information] Attempting to Load Rules from "C:\xampp\htdocs\rules.json" on AppReady 
11/22/2017 8:10:05 PM [Error] Can not start HTTP server at port 37408. Exception: One or more errors occurred.
11/22/2017 8:09:43 PM [Information] Running Plug-In "Papercut Seq Logging" "1.0.0.0" "Papercut Serilog to Seq (http://getseq.net) local instance" 
11/22/2017 8:09:43 PM [Information] Running Plug-In "Verbose (JSON) Serilog Logging" "1.0.0.0" "Verbose (JSON) Serilog Logging Support for Papercut" 
11/22/2017 8:09:43 PM [Information] Running Plug-In "WebUI" "1.0.0" "Provides a web UI to manage the email messages for Papercut." 
11/22/2017 8:09:17 PM [Information] Default Message Save Path is Set to "C:\Users\Jerome Greene\AppData\Roaming\Papercut" 
11/22/2017 8:09:17 PM [Information] Loading Messages from the Following Path(s) ["C:\Users\Jerome Greene\AppData\Roaming\Papercut", "C:\xampp\htdocs\", "C:\xampp\htdocs\Incoming"]

Am I missing something?
Thanks

**Comment by Jaben** [comment] 2017-12-07 03:40
Yeah, I'm going to close this thread since the issue is knowledge of PHP send mail -- not an issue with Papercut. I suggest the PHP tutorials for sendmail.

**Closed by Jaben** 2017-12-07 03:40 UTC
