### ISSUE TITLE
Papercutservice exception on run

### ISSUE THREAD

**Issue by timothies** [ChangemakerStudios/Papercut#80] opened 2017-09-21 04:36 UTC
Running Papercut on Azure VM and get exceptions when running

[14:24:38 INF] The PapercutServerService service is now running, press Control+C to exit.
[14:24:39 INF] Starting Server Smtp
[14:24:39 INF] Starting Server Papercut
[14:24:39 INF] Server Ready - Listening for New Connections 127.0.0.1:37403
[14:24:40 INF] Starting Server Smtp
[14:24:41 INF] Starting Server Smtp
[14:24:42 INF] Starting Server Smtp
[14:24:43 INF] Starting Server Smtp
[14:24:43 WRN] Unable to Create SMTP Server Listener on Any:25. After 5 Retries. Failing
System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Papercut.Network.Smtp.Server.CreateListener() in C:\projects\papercut\src\Papercut.Network\Smtp\Server.cs:line 159
   at Papercut.Network.Smtp.Server.Start() in C:\projects\papercut\src\Papercut.Network\Smtp\Server.cs:line 231
   at Papercut.Network.Smtp.ServerExtensions.<>c__DisplayClass0_0.<BindObservable>b__0(IObserver`1 o) in C:\projects\papercut\src\Papercut.Network\Smtp\ServerExtensions.cs:line 47
2017-09-21T04:26:25.8179522Z Exception while emitting periodic batch from Serilog.Sinks.Seq.SeqSink: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebExc
eption: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:5341
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception
)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Serilog.Sinks.Seq.SeqSink.<EmitBatchAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.<OnTick>d__16.MoveNext()
2017-09-21T04:31:47.8458607Z Exception while emitting periodic batch from Serilog.Sinks.Seq.SeqSink: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebExc

**Comment by jijiechen** [comment] 2017-09-21 04:48
Hi @timothies are you running desktop application with the service on the save machine with both listening on the 25 (default) port?
If so, a SMTP service of a later instance would fail.

The second exception seems caused by the `Seq` plugin. I think this can be safely ignored as it doesn't impact any functionalities. 

@Jaben  what's your opinions?

**Comment by Jaben** [comment] 2017-09-21 19:25
Yeah, you don't need the Seq plugin as you don't have a seq instance on that VM it appears.

Otherwise, check your ports and see what is listening to 25 on that server.

**Comment by Jaben** [comment] 2017-09-28 17:46
Look at this StackOverflow post to look at what is listening to port 25: https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows

Going to close this issue for now as it doesn't seem like a direct problem with Papercut Service.

**Closed by Jaben** 2017-09-28 17:46 UTC
