### ISSUE TITLE
Failed to End Receive on Async Socket

### ISSUE THREAD

**Issue by grohoskek** [ChangemakerStudios/Papercut#49] opened 2017-04-06 21:40 UTC
I'm attempting to use in a single server SharePoint farm and it's not working. The log says:

4/6/2017 4:34:00 PM [Warning] Failed to End Receive on Async Socket 
4/6/2017 4:33:38 PM [Information] Server Ready - Listening for New Connections "0.0.0.0":25 
4/6/2017 4:33:38 PM [Information] Starting Server Smtp

**Comment by Jaben** [comment] 2017-04-08 15:58
Hard to know what the issue is -- could you copy the "VerboseJsonLog" plugin to you papercut directory and re-run? In in any of the papercut release zips in the plugins directory: https://github.com/ChangemakerStudios/Papercut/releases

It will produce a logging json file with a lot of detail I can then upload into my local seq system.

**Comment by stuntbeaver** [comment] 2018-05-17 21:06
I am having the same problem too. Its running on a new Windows Server 2016 virtual machine, with .net framework 4.7.1. Logs below from a telnet session, I type "quit" and the session hangs in the telnet client.

```
2018-05-18 08:49:57.279 +12:00 [Debug] Status: 0 Connections "66.1MB" Memory Used
2018-05-18 08:54:55.674 +12:00 [Debug] Sending Line "220 devazsydutil01"
2018-05-18 08:54:55.674 +12:00 [Debug] New Connection 1 from "127.0.0.1:58243"
2018-05-18 08:54:55.674 +12:00 [Debug] Initializing Background Processes...
2018-05-18 08:55:04.979 +12:00 [Debug] Received Line "ehlo somedomain.com"
2018-05-18 08:55:04.983 +12:00 [Debug] Sending Line "250-devazsydutil01"
2018-05-18 08:55:04.984 +12:00 [Debug] Sending Line "250-SMTPUTF8"
2018-05-18 08:55:04.984 +12:00 [Debug] Sending Line "250-8BITMIME"
2018-05-18 08:55:04.984 +12:00 [Debug] Sending Line "250 OK"
2018-05-18 08:55:19.413 +12:00 [Debug] Received Line "mail from:me@somedomain.com"
2018-05-18 08:55:19.417 +12:00 [Debug] Sending Line "250 <me@somedomain.com> OK"
2018-05-18 08:55:29.083 +12:00 [Debug] Received Line "rcpt to:me@gmail.com"
2018-05-18 08:55:29.084 +12:00 [Debug] Sending Line "250 <me@gmail.com> OK"
2018-05-18 08:55:31.363 +12:00 [Debug] Received Line "data"
2018-05-18 08:55:31.367 +12:00 [Debug] Sending Line "354 Start mail input; end with <CRLF>.<CRLF>"
2018-05-18 08:55:41.979 +12:00 [Debug] Sending Line "250 OK"
2018-05-18 08:55:42.002 +12:00 [Warning] Failed to End Receive on Async Socket
System.FormatException: Failed to parse message headers.
   at MimeKit.MimeParser.ParseMessage(Byte* inbuf, CancellationToken cancellationToken)
   at MimeKit.MimeParser.ParseMessage(CancellationToken cancellationToken)
   at MimeKit.MimeMessage.Load(ParserOptions options, Stream stream, Boolean persistent, CancellationToken cancellationToken)
   at Papercut.Message.ReceivedDataMessageHandler.HandleReceived(String messageData, String[] recipients, Encoding connectionEncoding) in C:\projects\papercut\src\Papercut.Message\ReceivedDataMessageHandler.cs:line 58
   at Papercut.Network.SmtpCommands.DataSmtpCommand.Run(String command, String[] args) in C:\projects\papercut\src\Papercut.Network\SmtpCommands\DataSmtpCommand.cs:line 82
   at Papercut.Network.SmtpCommands.BaseSmtpCommand.Execute(ISmtpContext context, String request) in C:\projects\papercut\src\Papercut.Network\SmtpCommands\BaseSmtpCommand.cs:line 46
   at Papercut.Network.Protocols.SmtpProtocol.ProcessRequest(String request) in C:\projects\papercut\src\Papercut.Network\Protocols\SmtpProtocol.cs:line 59
   at Papercut.Network.Protocols.StringCommandProtocol.ProcessIncomingBuffer(Byte[] bufferedData, Encoding encoding) in C:\projects\papercut\src\Papercut.Network\Protocols\StringCommandProtocol.cs:line 64
   at Papercut.Network.Connection.ContinueProcessReceive(IAsyncResult result) in C:\projects\papercut\src\Papercut.Network\Connection.cs:line 138
2018-05-18 08:55:55.688 +12:00 [Debug] Status: 1 Connections "89MB" Memory Used

```

**Comment by jijiechen** [comment] 2018-05-18 00:04
I’ll try to reproduce it later.
I fixed a similar issue on the .NET Core version by this commit: https://github.com/ChangemakerStudios/Papercut/commit/92946621601493b44d66e912442cac96e55060d6

The issue was caused by missing handling of possible synchronized receiving in the **BeginReceive** method.

**Comment by stuntbeaver** [comment] 2019-02-13 23:05
I've tried to use the .net core version by pulling down jijiechen/papercut:latest, I've run exactly the same telnet based test and now have similar output.

docker run --name=papercut -p 25:25 -p 37408:37408 jijiechen/papercut:latest

`[22:59:01 WRN] Failed to End Receive on Async Socket
System.FormatException: Failed to parse message headers.
   at MimeKit.MimeParser.ParseMessage(Byte* inbuf)
   at MimeKit.MimeParser.ParseMessage(CancellationToken cancellationToken)
   at MimeKit.MimeMessage.Load(ParserOptions options, Stream stream, Boolean persistent, CancellationToken cancellationToken)
   at Papercut.Message.ReceivedDataMessageHandler.HandleReceived(String messageData, String[] recipients, Encoding connectionEncoding) in /home/travis/build/jijiechen/Papercut/src/Papercut.Message/ReceivedDataMessageHandler.cs:line 58
   at Papercut.Network.SmtpCommands.DataSmtpCommand.Run(String command, String[] args) in /home/travis/build/jijiechen/Papercut/src/Papercut.Network/SmtpCommands/DataSmtpCommand.cs:line 82
   at Papercut.Network.SmtpCommands.BaseSmtpCommand.Execute(ISmtpContext context, String request) in /home/travis/build/jijiechen/Papercut/src/Papercut.Network/SmtpCommands/BaseSmtpCommand.cs:line 46
   at Papercut.Network.Protocols.SmtpProtocol.ProcessRequest(String request) in /home/travis/build/jijiechen/Papercut/src/Papercut.Network/Protocols/SmtpProtocol.cs:line 59
   at Papercut.Network.Protocols.StringCommandProtocol.ProcessIncomingBuffer(Byte[] bufferedData, Encoding encoding) in /home/travis/build/jijiechen/Papercut/src/Papercut.Network/Protocols/StringCommandProtocol.cs:line 64
   at Papercut.Network.Connection.ContinueProcessReceive(SocketAsyncEventArgs result) in /home/travis/build/jijiechen/Papercut/src/Papercut.Network/Connection.cs:line 138`


This is the telnet commands i'm running:

220 4f9c337766bb
helo server.example.com
250 4f9c337766bb
mail from:aleith@my.example.com
250 <aleith@my.example.com> OK
rcpt to:aleith@gamil.com
250 <aleith@gamil.com> OK
data
354 Start mail input; end with <CRLF>.<CRLF>
Here we go!
Some subject body stuff

.
250 OK
quit

Typing 'quit' or 'QUIT'  after receiving the last 250 OK just hangs telnet.

**Comment by Jaben** [comment] 2019-03-19 03:42
Yeah, the above stack is still the old SMTP Server code. Try the newer code.

**Comment by Jaben** [comment] 2019-04-02 19:50
Closing this issue -- feel free to re-open if you are still having the problem.

**Comment by Jaben** [comment] 2019-04-02 19:50
Closing this issue -- feel free to re-open if you are still having the problem.

**Closed** 2019-04-02 19:53 UTC
Labels: question
