### ISSUE TITLE
PaperCut 5.5.1 - EHLO [IPv6:::1] fails with 501 syntax error

### ISSUE THREAD

**Issue by MircoBabin** [ChangemakerStudios/Papercut#155] opened 2019-10-18 07:10 UTC
**Describe the bug**
Using PaperCut to intercept SwiftMailer (PHP) messages.

SwiftMailer (incorrectly) detects my local domain as **[IPv6:::1]** and connects to PaperCut issuing:
**EHLO [IPv6:::1]**
**HELO [IPv6:::1]**

PaperCut responds with 501 syntax error

**To Reproduce**
1. Open dosprompt
2. telnet
3. open localhost 25
4. EHLO [IPv6:::1]
501 expected NOOP/RSET/QUIT/HELO/EHLO, 4 retry(ies) remaining.

**Expected behavior**
Expecting PaperCut to accept any domain name after EHLO and HELO. 

**Desktop (please complete the following information):**
 - OS: Windows/10 PRO
 - Version: 1903
 - Build: 18362.418

**Comment by primmy13** [comment] 2019-11-22 18:54
Not sure this is Papercut's "fault". I was experiencing the same issue in a similar environment, but finding https://laracasts.com/discuss/channels/laravel/ipv6-address-1-messed-up-swift-mailer-preventing-send-to-local-smtp-caputure-on-dev-machine addressed my issue.

To summarize the above link:  I had to modify my local Apache config to listen specifically over ipv4 ports (e.g. "Listen 0.0.0.0:80" rather than "listen 80"). Then, when accessing http://localhost, SwiftMailer will correctly detect that it should say hi to PaperCut at localhost/127.0.0.1 rather than IPv6::1.

**Comment by Jaben** [comment] 2020-04-03 16:54
Latest Papercut SMTP release (5.6.0) upgrade to latest SMTP server component... looks like this may be fixed: https://github.com/cosullivan/SmtpServer/commit/7364f68c20851c5cc19376d3dcb88cc50c26101a

Please try and let me know.

**Comment by primmy13** [comment] 2020-04-03 18:08
Sorry Jaben, I can't seem to replicate the original issue now. I suspect my network environment has changed a little, and I don't see a good way to reproduce it for the moment.

**Comment by Jaben** [comment] 2020-04-06 01:32
No worries -- but it should be fixed now. Re-open if you continue to have problems.

**Closed by Jaben** 2020-04-06 01:32 UTC

**Comment by agentlol** [comment] 2020-06-07 06:55
Probem is still there
>curl localhost:25
220 Papercut v6.5.0.0 ESMTP ready
501 expected NOOP/RSET/QUIT/HELO/EHLO, 4 retry(ies) remaining.
501 expected NOOP/RSET/QUIT/HELO/EHLO, 3 retry(ies) remaining.
501 expected NOOP/RSET/QUIT/HELO/EHLO, 2 retry(ies) remaining.
501 expected NOOP/RSET/QUIT/HELO/EHLO, 1 retry(ies) remaining.
501 expected NOOP/RSET/QUIT/HELO/EHLO, 0 retry(ies) remaining.
